[ClientInfo]
client = 
Qradar_url = 
QRadar_token = 

[SOCInfo]
TheHive_url = 
H_API_KEY = 

[ConfigInfo]
#! Number of offenses to be imported
nbr_offenses = 50
#! Number of seconds between offense api requests
nbr_sec = 60 
#! Number of seconds between api timeouts
nbr_sec_timeout = 5
#! Maximum number of observables to get
limit_art = 15 
#! Max size of log before compression
max_comp_size = 1000000000

[LogInfo]
#! Dict name
id_dict_f = /opt/Hscripts/conf/ids_CLIENT_QH.json
#! log file
log_file = /var/log/Qhive/qhive.log
#! errors log file
err_log_file = /var/log/Qhive/qhive_err.log
